<?php

// autoload-files.php @generated by Strauss
// @see https://github.com/BrianHenryIE/strauss/

require_once __DIR__ . '/razorpay/razorpay/Deprecated.php';
require_once __DIR__ . '/rmccue/requests/library/Deprecated.php';
require_once __DIR__ . '/ssnepenthe/color-utils/inc/colors.php';
require_once __DIR__ . '/ssnepenthe/color-utils/inc/helpers.php';
require_once __DIR__ . '/ssnepenthe/color-utils/inc/transformations.php';
