<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-controls',
	'deps' => [
		'elementor-v2-editor-props',
		'elementor-v2-icons',
		'elementor-v2-session',
		'elementor-v2-ui',
		'elementor-v2-utils',
		'elementor-v2-wp-media',
		'react',
		'wp-i18n',
	],
];
