<?php

// autoload-classmap.php @generated by Strauss

$strauss_src = dirname(__FILE__);

return array(
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\JoinQueryBuilder' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/JoinQueryBuilder.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\QueryBuilder' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/QueryBuilder.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\WhereQueryBuilder' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/WhereQueryBuilder.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Types\Type' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Types/Type.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Types\Operator' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Types/Operator.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Types\JoinType' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Types/JoinType.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Types\Math' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Types/Math.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Concerns\HavingClause' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Concerns/HavingClause.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Concerns\WhereClause' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Concerns/WhereClause.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Concerns\FromClause' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Concerns/FromClause.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Concerns\OrderByStatement' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Concerns/OrderByStatement.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Concerns\MetaQuery' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Concerns/MetaQuery.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Concerns\OffsetStatement' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Concerns/OffsetStatement.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Concerns\UnionOperator' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Concerns/UnionOperator.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Concerns\SelectStatement' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Concerns/SelectStatement.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Concerns\TablePrefix' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Concerns/TablePrefix.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Concerns\CRUD' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Concerns/CRUD.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Concerns\Aggregate' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Concerns/Aggregate.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Concerns\JoinClause' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Concerns/JoinClause.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Concerns\GroupByStatement' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Concerns/GroupByStatement.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Concerns\LimitStatement' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Concerns/LimitStatement.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Clauses\JoinCondition' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Clauses/JoinCondition.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Clauses\RawSQL' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Clauses/RawSQL.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Clauses\Join' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Clauses/Join.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Clauses\OrderBy' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Clauses/OrderBy.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Clauses\MetaTable' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Clauses/MetaTable.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Clauses\From' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Clauses/From.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Clauses\Having' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Clauses/Having.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Clauses\Where' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Clauses/Where.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Clauses\Union' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Clauses/Union.php',
   'LearnDash\Achievements\StellarWP\DB\QueryBuilder\Clauses\Select' => $strauss_src . '/stellarwp/db/src/DB/QueryBuilder/Clauses/Select.php',
   'LearnDash\Achievements\StellarWP\DB\Database\Actions\EnableBigSqlSelects' => $strauss_src . '/stellarwp/db/src/DB/Database/Actions/EnableBigSqlSelects.php',
   'LearnDash\Achievements\StellarWP\DB\Database\Provider' => $strauss_src . '/stellarwp/db/src/DB/Database/Provider.php',
   'LearnDash\Achievements\StellarWP\DB\Database\Exceptions\DatabaseQueryException' => $strauss_src . '/stellarwp/db/src/DB/Database/Exceptions/DatabaseQueryException.php',
   'LearnDash\Achievements\StellarWP\DB\DB' => $strauss_src . '/stellarwp/db/src/DB/DB.php',
   'LearnDash\Achievements\StellarWP\DB\Config' => $strauss_src . '/stellarwp/db/src/DB/Config.php',
);